name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy to the staging cluster
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}"" > ~/ssh_key
          ssh -i ~/ssh_key root@35.175.193.89
          cd monorepo-deployment/ && git pull
          pnpm install
          pnpm run build
          pm2 restart fe-server
          pm2 restart ws-server
          pm2 restart http-server
