name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy to the staging cluster
    runs-on: ubuntu-latest
    steps:
      - name: Deplou via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 35.175.193.89
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd monorepo-deployment/
            git pull
            pnpm install
            pnpm run build
            pm2 restart fe-server
            pm2 restart ws-server
            pm2 restart http-server
